server:
  port: 8082
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&amp&useSSL=false
#    username: root
#    password:
mybatis:
  type-aliases-package: cn.com.proinnova.epidemic.bean
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
deadnum: 10