server:
  port: 8082
mybatis:
  type-aliases-package: cn.com.proinnova.epidemic.bean
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.com.proinnova.epidemic.dao: debug
deadnum: 10
