server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&amp&useSSL=false
    username: root
    password:
mybatis:
  type-aliases-package: cn.com.proinnova.bean
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true